import { ReactNode } from "react";
import SideBar from "./component/SideBar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode
}




export default function Layout({ children }: RootLayoutProps) {
  return (

    <ClerkProvider>
    <div className="flex h-screen max-w-[1440px] mx-auto">
          <SideBar/>
          <div className="flex-grow">
             {children}
          </div>
    </div>
    </ClerkProvider>
  );
}
