import { ReactNode } from "react";
import "./globals.css";
import StoreDataProvider from "./store/StoreContext";
import Footer from "./component/Footer/Footer";
import Nav from "./component/Header/Nav";
import {ToastContainer} from 'react-toastify'
import { SpeedInsights } from "@vercel/speed-insights/next"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreDataProvider>
          <Nav />
          <ToastContainer position="top-right" autoClose={5000} />
          {children}
          <SpeedInsights/>
          <Footer />
        </StoreDataProvider>
      </body>
    </html>
  );
}
