import { ReactNode } from "react";
import "./globals.css";
import StoreDataProvider from "./store/StoreContext";
import Nav from "@/component/Header/Nav";
import Footer from "@/component/Footer/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreDataProvider>
          <Nav />
          {children}
          <Footer />
        </StoreDataProvider>
      </body>
    </html>
  );
}
